// Code generated by mockery v1.0.0. DO NOT EDIT.

package discogs

import mock "github.com/stretchr/testify/mock"
import services "app/internal/discogs/services"

// MockDiscogs is an autogenerated mock type for the Discogs type
type MockDiscogs struct {
	mock.Mock
}

// Artist provides a mock function with given fields:
func (_m *MockDiscogs) Artist() services.ArtistService {
	ret := _m.Called()

	var r0 services.ArtistService
	if rf, ok := ret.Get(0).(func() services.ArtistService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(services.ArtistService)
		}
	}

	return r0
}

// Masters provides a mock function with given fields:
func (_m *MockDiscogs) Masters() services.MastersService {
	ret := _m.Called()

	var r0 services.MastersService
	if rf, ok := ret.Get(0).(func() services.MastersService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(services.MastersService)
		}
	}

	return r0
}

// Search provides a mock function with given fields:
func (_m *MockDiscogs) Search() services.SearchService {
	ret := _m.Called()

	var r0 services.SearchService
	if rf, ok := ret.Get(0).(func() services.SearchService); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(services.SearchService)
		}
	}

	return r0
}
