version: "2"

services:
  db:
    image: postgres:9.6
    ports:
      - 54321:5432
    volumes:
      - ./local/data:/var/lib/postgres
    environment:
      POSTGRES_DB: vinyl-analytics
      POSTGRES_USER: vinyl
      POSTGRES_PASSWORD: secret
  api:
    image: golang:1.11.5
    volumes:
      - .:/Users/maxheckel/Sites/vinyl-analytics/api
    working_dir: /Users/maxheckel/Sites/vinyl-analytics/api
    env_file:
      - ./.env
    command: |-
      bash -c '
      set -ex; apt-get update; apt-get install -y php7.0-fpm php7.0-curl; go get -u github.com/codegangsta/gin; gin \
              -i \
              -d server/cmd/app \
              -x vendor \
              --appPort 8081 \
              run server/cmd/app/main.go'
    ports:
      - 8081:8081
  ui:
    image: node:10-alpine
    volumes:
      - .:/Users/maxheckel/Sites/vinyl-analytics/ui
    working_dir: /Users/maxheckel/Sites/vinyl-analytics/ui
    command: sh -c "cd ui && npm install && npm run serve"
    ports:
      - 8080:8080

  migrate:
    image: golang:1.11.5
    depends_on:
      - db
    volumes:
      - .:/Users/maxheckel/Sites/vinyl-analytics/api
    working_dir: /Users/maxheckel/Sites/vinyl-analytics/api
    command: |-
      bash -c './server/scripts/wait-for-it.sh db:5432 && cd server && go run cmd/migrate/main.go'