// Code generated by mockery v1.0.0. DO NOT EDIT.

package handlers

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockHandlers is an autogenerated mock type for the Handlers type
type MockHandlers struct {
	mock.Mock
}

// DiscoverAlbums provides a mock function with given fields: writer, request
func (_m *MockHandlers) DiscoverAlbums(writer http.ResponseWriter, request *http.Request) {
	_m.Called(writer, request)
}

// GetAlbum provides a mock function with given fields: writer, request
func (_m *MockHandlers) GetAlbum(writer http.ResponseWriter, request *http.Request) {
	_m.Called(writer, request)
}

// GetAlbums provides a mock function with given fields: writer, request
func (_m *MockHandlers) GetAlbums(writer http.ResponseWriter, request *http.Request) {
	_m.Called(writer, request)
}
