// Code generated by mockery v1.0.0. DO NOT EDIT.

package services

import mock "github.com/stretchr/testify/mock"
import models "app/internal/discogs/models"

// MockMastersService is an autogenerated mock type for the MastersService type
type MockMastersService struct {
	mock.Mock
}

// GetMaster provides a mock function with given fields: id
func (_m *MockMastersService) GetMaster(id uint) (*models.Master, error) {
	ret := _m.Called(id)

	var r0 *models.Master
	if rf, ok := ret.Get(0).(func(uint) *models.Master); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Master)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
